name: Metrics
on:
  # Agenda atualizações diárias
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente
  workflow_dispatch:
  # Roda a cada commit no master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Seu token (O GitHub gerencia isso automaticamente)
          token: ${{ secrets.GITHUB_TOKEN }}

          # Opções principais
          user: RoberthFurtadoDev
          template: classic
          # A "mágica" está aqui: usamos apenas a base 'activity' para o radar chart
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # Nome do arquivo gerado
          filename: github-metrics.svg
