name: Metrics
on:
  # Atualiza diariamente
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Configuração Básica
          user: RoberthFurtadoDev
          template: classic
          filename: github-metrics.svg
          config_timezone: America/Sao_Paulo
          
          # GARANTE QUE NÃO TERÁ POLUIÇÃO VISUAL
          base: ""
          
          # ATIVA O GRÁFICO DE RADAR/CRUZ EXATO QUE VOCÊ QUER
          plugin_introduction: yes
          plugin_introduction_title: no # Remove o título para ficar só o gráfico