name: Metrics
on:
  # Agenda atualizações diárias
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente
  workflow_dispatch:
  # Roda a cada commit no master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Seu token (NÃO PRECISA EDITAR SE FOR NO SEU PRÓPRIO REPO, O GITHUB JÁ SABE)
          token: ${{ secrets.GITHUB_TOKEN }}

          # Opções principais
          user: RoberthFurtadoDev
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # Plugin: Isocalendar (O gráfico isométrico premium)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Plugin: Languages (Mostra suas linguagens com design clean)
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          
          # Plugin: Habits (Gráficos de dia/hora de commit)
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          
          # Visual
          config_display: large
          filename: github-metrics.svg
