name: Metrics
on:
  # Atualiza diariamente
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Configuração Básica
          user: RoberthFurtadoDev
          template: classic
          config_timezone: America/Sao_Paulo
          filename: github-metrics.svg
          
          # TRUQUE: Desativamos a 'base' para não mostrar bio/seguidores/avatar
          base: ""
          
          # Ativamos APENAS o plugin followup (O gráfico de radar/cruz que você quer)
          plugin_followup: yes
          plugin_followup_sections: repositories