name: ğŸ GitHub Contribution Snake

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # roda uma vez por dia, pode ajustar

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v3

      - name: ğŸ Gerar animaÃ§Ã£o da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: RoberthFurtadoDev
          outputs: |
            dist/github-contribution-snake.svg
            dist/github-contribution-snake-dark.svg

      - name: ğŸ“¤ Commit e push dos SVGs
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: atualiza snake.svg"
          add: "dist/*.svg"
