name: ğŸ GitHub Contribution Snake

on:
  schedule:
    # roda a cada hora (ajuste o cron como quiser)
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # faz checkout do repo
      - uses: actions/checkout@v3

      # gera o snake SVG na pasta `output/`
      - name: ğŸ Run GitHub Contribution Snake
        uses: andstor/github-contribution-snake-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # onde salvar o SVG gerado
          output_path: 'output'
